#!/usr/bin/env bash
set -oueE pipefail

if [[ "$*" == *"--rootd"* ]]; then
    SYSROOT="${*: -1}"
else
    SYSROOT=""
fi

source "$SYSROOT/etc/repo/repo.conf" || :

REPO_IMAGE="${REPO_IMAGE:-ghcr.io/nostale3210/repo-utils:latest}"
MAX_DEPS="${MAX_DEPS:-4}"
HOSTONLY_INITRD="${HOSTONLY_INITRD:-1}"
SUBCMD="${1-none}"
SUBARG="${2-none}"
SUBSUBARG="${3-none}"

get_pkg_list() {
    local list="$1"

    printf "%s" "$(cat "$list" | grep -v -e "^#" -e "^\s*$")"
}

get_pm_transaction() {
    local mockdir="$1"
    local pkgs="$2"
    case "$PACKAGE_MANAGER" in
        "dnf")
            get_dnf_transaction "$mockdir" "$pkgs"
            ;;
    esac
}

get_dnf_transaction() {
    local mockdir="$1"
    local pkgs="$2"
    read -ra pkg_array <<< "$(tr "\n" " " <<< "$pkgs")"

    local transaction
    transaction="$(podman exec --privileged repo-build \
        dnf install --assumeno --cacheonly --use-host-config --installroot "$mockdir" "${pkg_array[@]}")" || :
    transaction="$(grep "^\s[a-zA-Z0-9].*" <<< "$transaction" | grep -v "^\sInstalling.*")"
    awk '$5 ~ /.+/' <<< "$transaction" | awk '{print $1"@"$3"."$2}'
}

pm_download() {
    local pkg="$1"
    local pkg_name="$2"
    case "$PACKAGE_MANAGER" in
        "dnf")
            dnf_download "$pkg" "$pkg_name"
            ;;
    esac
}

dnf_download() {
    local pkg="$1"
    local pkg_name="$2"
    podman exec --privileged repo-build bash -c "dnf download -y --destdir /tmp ${pkg//@/-} &&
    mv -f /tmp/$pkg_name*.rpm /.repo/store/$pkg.rpm &&
    touch /.repo/store/$pkg.repo-lock"
}

exists_or_install() {
    local pkg="$1"
    IFS="@" read -ra pkg_split <<< "$pkg"

    export SYSROOT
    for i in {0..3}; do
        if [[ -f "$SYSROOT/.repo/store/$pkg.repo-lock" ]]; then
            printf "%s found in store\n" "$pkg"
            break
        else
            if [[ "$i" == "3" ]]; then
                printf "%s (%s) couldn't be downloaded\n" "$pkg" "${pkg_split[0]}"
                exit 255;
            fi
            sleep "$((i*3))"
            pm_download "$pkg" "${pkg_split[0]}"
        fi
    done
    export -n SYSROOT
}

populate_store() {
    local pm_transaction="$1"
    printf "%s" "$pm_transaction" | xargs -P"$(nproc)" -I{} \
        bash -c 'exists_or_install "$@"' _ {} ||
        { printf "Couldn't install some packages. Exiting...\n"; exit 1; }
}

get_deployments() {
    printf "%s" "$(find "$SYSROOT/.repo/deployments" -mindepth 1 -maxdepth 1 -regex ".*/[0-9]+" | \
        awk -F"/" '{print $NF}')"
}

get_all_deployments() {
    in_boot="$(find "$SYSROOT/boot" -mindepth 1 -maxdepth 1 -type d -printf "%f\n" 2>/dev/null | \
        grep "^[0-9]*$")" || :
    in_entries="$(find "$SYSROOT/boot/loader/entries" -mindepth 1 -maxdepth 1 -type f -printf "%f\n" 2>/dev/null | \
        grep "^[0-9]*.conf$" | \
        sed "s/.conf$//")" || :
    in_ukis="$(find "$SYSROOT/boot/EFI/Linux" -mindepth 1 -maxdepth 1 -type f -printf "%f\n" 2>/dev/null | \
        grep "^[0-9]*.efi$" | \
        sed "s/.efi$//")" || :
    in_deps="$(find "$SYSROOT/.repo/deployments" -mindepth 1 -maxdepth 1 -type d -printf "%f\n" 2>/dev/null | \
        grep "^[0-9]*$")" || :
    printf "%s\n%s\n%s\n%s\n" "$in_boot" "$in_entries" "$in_ukis" "$in_deps" |
        grep -v "^\s*$" |
        sort -un
}

get_dep_intact() {
    local deployment="$1"
    local boot
    local dep
    if [[ -d "$SYSROOT/boot/$deployment" && -f "$SYSROOT/boot/loader/entries/$deployment.conf" ]]; then
        boot="1"
    else
        boot="0"
    fi
    if [[ -f "$SYSROOT/boot/EFI/Linux/$deployment.efi" && "$boot" == "0" ]]; then
        boot="1"
    fi
    if [[ -d "$SYSROOT/.repo/deployments/$deployment" ]]; then
        dep="1"
    else
        dep="0"
    fi
    if [[ "$boot" == "1" && "$dep" == "1" ]]; then
        printf "1"
    else
        printf "0"
    fi
}

get_dep_status() {
    local deployment="$1"
    local intact
    intact="$(get_dep_intact "$deployment")"
    if [[ "$intact" == "0" ]]; then
        printf "Deployment %s:\n\tdefective\n" "$deployment"
    else
        local kernel
        local created
        local active=""
        kernel="$(ls "$SYSROOT/.repo/deployments/$deployment/usr/lib/modules")"
        created="$(stat --printf "%y" "$SYSROOT/.repo/deployments/$deployment")"
        if [[ "$(cat "$SYSROOT/usr/.repo")" == "$deployment" ]]; then
            active=" (active)";
        fi
        printf "Deployment %s:%s\n\tKernel: %s\n\tCreated: %s\n" \
            "$deployment" "$active" "$kernel" "$created"
    fi
}

get_dep_stati() {
    local deployment="$1"
    if [[ "$deployment" == "none" || "$deployment" == "--rootd" ]]; then
        export -f get_dep_status
        export -f get_dep_intact
        export SYSROOT
        printf "\n"
        get_all_deployments | tac | xargs -I{} bash -c "get_dep_status {} && printf '\n'"
        export -n get_dep_status
        export -n get_dep_intact
        export -n SYSROOT
    else
        get_dep_status "$1"
    fi
}

gc_defective() {
    local all_deps
    all_deps="$(get_all_deployments)"
    read -ra all_deps_arr <<< "$(printf "%s\n" "$all_deps" | tr "\n" " ")"
    for dep in "${all_deps_arr[@]}"; do
        local intact
        intact="$(get_dep_intact "$dep")"
        if [[ "$intact" == "0" ]]; then
            cleanup_dep "$dep" 2>/dev/null
        fi
    done
}

gc_all() {
    local opts="$1"
    if [[ "$opts" == "none" || "$opts" =~ broken ]]; then
        printf "Collecting broken deployments...\n"
        gc_defective
    fi

    if [[ "$opts" == "none" || "$opts" =~ deps ]]; then
        printf "Collecting old deployments...\n"
        local current_deps
        local current_deps_num
        current_deps="$(get_all_deployments)"
        current_deps_num="$(wc -l <<< "$current_deps")"
        while [[ "$current_deps_num" -gt "$MAX_DEPS" ]]; do
            local dep
            dep="$(head -n1 <<< "$current_deps")"
            printf "Collecting deployment %s...\n" "$dep"
            cleanup_dep "$dep" 2>/dev/null
            current_deps="$(get_all_deployments)"
            current_deps_num="$(wc -l <<< "$current_deps")"
        done
    fi

    if [[ "$opts" == "none" || "$opts" =~ store ]]; then
        printf "Finding orphans in store...\n"
        find_orphans "rm"
    fi
}

diff_deps() {
    local dep1="$1"
    local dep2="$2"

    local latest
    local snd_latest
    latest="$(get_all_deployments | tac | sed "1q;d")"
    snd_latest="$(get_all_deployments | tac | sed "2q;d")"
    if [[ "$dep1" == "none" && "$dep2" == "none" ]]; then
        dep2="$latest"
        dep1="$snd_latest"
    elif [[ "$dep1" != "none" && "$dep2" == "none" ]]; then
        if [[ "$dep1" == "$latest" ]]; then
            dep1="$snd_latest"
        fi
        dep2="$latest"
    fi

    printf "Comparing deployments %s and %s:\n" "$dep1" "$dep2"
    diff -y "$SYSROOT/.repo/deployments/$dep1/pkgs" "$SYSROOT/.repo/deployments/$dep2/pkgs" |
        grep "<\||\|>" || :
}

get_next_deployment() {
    local deployments
    deployments="$(get_deployments)"
    if [[ "$deployments" == "" ]]; then
        printf "0"
    else
        printf "%s" "$(($(sort -rn <<< "$deployments" | head -n1)+1))"
    fi
}

container_setup() {
    case "$PACKAGE_MANAGER" in
        "dnf")
            podman exec --privileged repo-build dnf install -y dnf5-plugins
            ;;
    esac
}

container_metadata_update() {
    case "$PACKAGE_MANAGER" in
        "dnf")
            podman exec --privileged repo-build dnf check-upgrade --refresh -y
            podman exec --privileged repo-build dnf makecache -y
            podman exec --privileged repo-build \
                dnf check-upgrade --refresh -y --use-host-config --installroot /empty
            podman exec --privileged repo-build \
                dnf makecache -y --use-host-config --installroot /empty
            ;;
    esac
}

create_deployment() {
    local pm_transaction="$1"
    local options="$2"
    local prev_dep
    local next_dep
    next_dep="$(get_next_deployment)"
    prev_dep="$((next_dep-1))"

    trap 'cleanup_dep "$next_dep" 2>/dev/null' INT TERM ERR

    printf "Creating deployment %s...\n" "$next_dep"

    podman exec --privileged repo-build bash -c "mkdir -p /tmp/$next_dep/{usr,etc}"

    export next_dep
    install_packages "$next_dep" "$pm_transaction" :

    podman exec --privileged repo-build cp /scripts/post.sh "/tmp/$next_dep/post.sh"

    install_repo "$next_dep"

    if [[ "$next_dep" == "0" || "$prev_dep" == "0" ]]; then
        mv -f "/tmp/$next_dep" "$SYSROOT/.repo/deployments/$next_dep"
    else
        mkdir -p "$SYSROOT/.repo/deployments/$next_dep/"{usr,etc}
        printf "Hardlinking previous deployment...\n"
        rsync -aHlx --link-dest="../../$prev_dep/usr/" "$SYSROOT/.repo/deployments/$prev_dep/usr/" "$SYSROOT/.repo/deployments/$next_dep/usr/"

        printf "Syncing previous config...\n"
        rsync -aHlx "$SYSROOT/.repo/deployments/$prev_dep/etc/" "$SYSROOT/.repo/deployments/$next_dep/etc/"

        printf "Syncing next directory skeleton...\n"
        rsync -ac -f"+ */" -f"- *" --delete "/tmp/$next_dep/" "$SYSROOT/.repo/deployments/$next_dep/"

        printf "Syncing next deployment to disk...\n"
        find "/tmp/$next_dep" -not -type d -printf "%s\t%p\n" |
            sort -nr | cut -f2- | sed "s/^\(\/tmp\/$next_dep\)/\1\/./g" |
            grep -e "^/tmp/$next_dep/\./usr" -e "^/tmp/$next_dep/\./etc" \
            -e "^/tmp/$next_dep/\./bin" -e "^/tmp/$next_dep/\./sbin" \
            -e "^/tmp/$next_dep/\./lib" -e "^/tmp/$next_dep/\./lib64" |
            xargs -n5000 -P"$(nproc)" \
            bash -c 'sysroot="$0" && shift && rsync -aHlcx --delete --relative --ignore-missing-args "$@" "$sysroot/.repo/deployments/$next_dep/"' "$SYSROOT" _

        printf "Trimming image...\n"
        local dirty
        local clean
        dirty="$(find "$SYSROOT/.repo/deployments/$next_dep/usr" "$SYSROOT/.repo/deployments/$next_dep/etc" | sed "s|^$SYSROOT/.repo/deployments/$next_dep||g" | sort)"
        clean="$(find "/tmp/$next_dep/usr" "/tmp/$next_dep/etc" | sed "s/^\/tmp\/$next_dep//g" | sort)"
        comm -23 <(printf "%s" "$dirty") <(printf "%s" "$clean") |
            sed "s|^|$SYSROOT/.repo/deployments/$next_dep|g" | xargs rm -rf
    fi

    rm -rf "/tmp/$next_dep"

    mkdir -p "$SYSROOT/.repo/deployments/$next_dep/"{dev,proc,run,sys,tmp}
    mount -t proc /proc "$SYSROOT/.repo/deployments/$next_dep/proc/"
    mount -t sysfs /sys "$SYSROOT/.repo/deployments/$next_dep/sys/"
    mount -t tmpfs tmpfs "$SYSROOT/.repo/deployments/$next_dep/tmp/"
    mount --bind /dev "$SYSROOT/.repo/deployments/$next_dep/dev/"
    mount --bind /run "$SYSROOT/.repo/deployments/$next_dep/run/"
    mount --bind /sys/firmware/efi/efivars "$SYSROOT/.repo/deployments/$next_dep/sys/firmware/efi/efivars/"

    printf "Running post script...\n"
    if [[ -f "$SYSROOT/etc/repo/scripts/post.sh" ]]; then
        cp "$SYSROOT/etc/repo/scripts/post.sh" "$SYSROOT/.repo/deployments/$next_dep/post.sh"
        chroot "$SYSROOT/.repo/deployments/$next_dep" \
            /usr/bin/env "PATH=/usr/bin" bash /post.sh
    fi

    system_config "$next_dep" "$options"

    if [[ "$HOSTONLY_INITRD" == "1" ]]; then
        install_hostonly_initrd "$next_dep"
    fi

    mkdir "$SYSROOT/boot/$next_dep"
    boot_files "$next_dep"

    case "$PACKAGE_MANAGER" in
        "dnf")
            selinux_policy "$next_dep"
            ;;
    esac

    umount -Rfl "$SYSROOT/.repo/deployments/$next_dep/"* 2>/dev/null || :

    printf "%s" "$pm_transaction" > "$SYSROOT/.repo/deployments/$next_dep/pkgs"
    printf "%s" "$next_dep" > "$SYSROOT/.repo/deployments/$next_dep/usr/.repo"

    export -n next_dep

    if [[ "$options" =~ activate ]]; then
        printf "Activating deployment %s\n" "$next_dep"
        activate_dep "$next_dep"
    fi
}

system_config() {
    local deployment="$1"
    local options="$2"

    printf "Syncing system config...\n"
    find "$SYSROOT/.repo/deployments/$deployment/etc" -mindepth 1 -execdir sh -c "touch -d @0 '{}' &>/dev/null || :" \;

    if [[ ! "$options" =~ drop ]]; then
        find "$SYSROOT/etc" -newermt @0 -print0 2>/dev/null | xargs -0 -I{} cp -fa --parents {} "$SYSROOT/.repo/deployments/$deployment/" || :
    fi

    cp -rfa --parents "$SYSROOT/etc/fstab" "$SYSROOT/etc/crypttab" "$SYSROOT/etc/locale.conf" \
        "$SYSROOT/etc/localtime" "$SYSROOT/etc/adjtime" "$SYSROOT/etc/sudoers.d" \
        "$SYSROOT/etc/group" "$SYSROOT/etc/gshadow" "$SYSROOT/etc/subgid" "$SYSROOT/etc/subuid" \
        "$SYSROOT/etc/NetworkManager/system-connections" "$SYSROOT/etc/vconsole.conf" \
        "$SYSROOT/etc/pki" "$SYSROOT/etc/firewalld" "$SYSROOT/etc/environment" \
        "$SYSROOT/etc/hostname" "$SYSROOT/etc/X11/xorg.conf.d/00-keyboard.conf" \
        "$SYSROOT/etc/sudoers" "$SYSROOT/etc/repo" \
        "$SYSROOT/.repo/deployments/$deployment/" 2>/dev/null || :

    sort "$SYSROOT/etc/passwd" "$SYSROOT/.repo/deployments/$deployment/etc/passwd" | awk -F':' '!a[$1]++' > "$SYSROOT/.repo/deployments/$deployment/etc/passwd.tmp" &&
        mv "$SYSROOT/.repo/deployments/$deployment/etc/passwd.tmp" "$SYSROOT/.repo/deployments/$deployment/etc/passwd"
    sort "$SYSROOT/etc/shadow" "$SYSROOT/.repo/deployments/$deployment/etc/shadow" | awk -F':' '!a[$1]++' > "$SYSROOT/.repo/deployments/$deployment/etc/shadow.tmp" &&
        mv "$SYSROOT/.repo/deployments/$deployment/etc/shadow.tmp" "$SYSROOT/.repo/deployments/$deployment/etc/shadow"
    sort "$SYSROOT/etc/group" "$SYSROOT/.repo/deployments/$deployment/etc/group" | awk -F':' '!a[$1]++' > "$SYSROOT/.repo/deployments/$deployment/etc/group.tmp" &&
        mv "$SYSROOT/.repo/deployments/$deployment/etc/group.tmp" "$SYSROOT/.repo/deployments/$deployment/etc/group"
}

boot_files() {
    local deployment="$1"

    printf "Placing kernel and initramfs...\n"
    kernel="$(find "$SYSROOT/.repo/deployments/$deployment/usr/lib/modules" -name vmlinuz | sort | tail -n1)"
    initrd="$(find "$SYSROOT/.repo/deployments/$deployment/usr/lib/modules" -name initramfs.img | sort | tail -n1)"

    local boot_type
    if hash ukify; then
        local cmdline
        boot_type="uki"
        cmdline="$(cat "$SYSROOT/etc/repo/boot.conf" | \
            grep "^options " | \
            sed "s/^options //" | \
            sed "s/INSERT_DEPLOYMENT/$deployment/g")"
        ukify build --linux="$kernel" --initrd="$initrd" \
            --cmdline="$cmdline" --output="$SYSROOT/boot/EFI/Linux/$deployment.efi"
    else
        boot_type="default"
        cp -fa "$kernel" "$SYSROOT/boot/$deployment/vmlinuz"
        cp -fa "$initrd" "$SYSROOT/boot/$deployment/initramfs.img"

        printf "Creating boot entry...\n"
        cat "$SYSROOT/etc/repo/boot.conf" | sed "s/INSERT_DEPLOYMENT/$deployment/g" > "$SYSROOT/boot/loader/entries/$deployment.conf"
    fi

    if hash sbctl && [[ -d "$SYSROOT/var/lib/sbctl" ]]; then
        if [[ "$boot_type" == "uki" ]]; then
            sbctl sign "$SYSROOT/boot/EFI/Linux/$deployment.efi"
        else
            sbctl sign "$SYSROOT/boot/$deployment/vmlinuz"
        fi
    fi
}

install_repo() {
    local deployment="$1"
    podman create --privileged --replace --pull newer --name repo-tmp "$REPO_IMAGE"
    podman cp repo-tmp:/app/repo "/tmp/$deployment/usr/bin/repo"
    podman cp repo-tmp:/app/move-mount "/tmp/$deployment/usr/bin/move-mount"
    podman cp repo-tmp:/app/init/repo-boot.sh "/tmp/$deployment/usr/libexec/repo-boot.sh"
    chmod +x "/tmp/$deployment/usr/libexec/repo-boot.sh"

    case "$PACKAGE_MANAGER" in
        "dnf")
            podman cp repo-tmp:/app/init/90repo "/tmp/$deployment/usr/lib/dracut/modules.d/90repo"
            podman cp repo-tmp:/app/init/repo-boot.service "/tmp/$deployment/usr/lib/systemd/system/repo-boot.service"
            ;;
    esac

    podman rm repo-tmp
}

init_repo() {
    podman create --privileged --replace --pull newer --name repo-tmp "$REPO_IMAGE"

    podman cp repo-tmp:/app/repo "$SYSROOT/usr/bin/repo"
    podman cp repo-tmp:/app/move-mount "$SYSROOT/usr/bin/move-mount"
    podman cp repo-tmp:/app/init/repo-boot.sh "$SYSROOT/usr/libexec/repo-boot.sh"
    chmod +x "$SYSROOT/usr/libexec/repo-boot.sh"

    case "$PACKAGE_MANAGER" in
        "dnf")
            podman cp repo-tmp:/app/init/90repo "$SYSROOT/usr/lib/dracut/modules.d/90repo"
            podman cp repo-tmp:/app/init/repo-boot.service "$SYSROOT/usr/lib/systemd/system/repo-boot.service"
            ;;
    esac

    mkdir -p "$SYSROOT/.repo/"{store,deployments/0}
    mkdir -p "$SYSROOT/etc/repo"
    podman cp repo-tmp:/app/repo.conf "$SYSROOT/etc/repo/repo.conf"
    podman cp repo-tmp:/app/list.pkgs "$SYSROOT/etc/repo/list.pkgs"
    podman cp repo-tmp:/app/scripts "$SYSROOT/etc/repo/scripts"

    podman rm repo-tmp
}

install_packages() {
    local deployment="$1"
    local pm_transaction
    pm_transaction="$(sed "s/\(.*\)$/\/.repo\/store\/\1/" <<< "$2")"
    case "$PACKAGE_MANAGER" in
        "dnf")
            pm_transaction="$(sed "s/$/.rpm/" <<< "$pm_transaction")"
            read -ra pkg_array <<< "$(tr "\n" " " <<< "$pm_transaction")"
            podman exec --privileged repo-build dnf install -y --installroot="/tmp/$deployment" "${pkg_array[@]}" || :
            ;;
    esac
}

install_hostonly_initrd() {
    local deployment="$1"
    if [[ ! -f "$SYSROOT/usr/.repo" ]]; then
        printf "Generating a hostonly initramfs on non-repo systems is not supported. Exiting...\n"
        exit 1
    fi

    case "$PACKAGE_MANAGER" in
        "dnf")
            dracut_initrd "$deployment"
            ;;
        *)
            printf "Generating a hostonly initramfs on non-repo systems is not supported. Exiting...\n"
            exit 1
            ;;
    esac
}

dracut_initrd() {
    local deployment="$1"
    local kver
    kver="$(ls "$SYSROOT/.repo/deployments/$deployment/usr/lib/modules")"
    mount --bind "$SYSROOT/.repo/deployments/$deployment/usr/lib/modules" "$SYSROOT/usr/lib/modules"
    dracut --hostonly --kver "$kver" --reproducible --add "repo" \
        -f "$SYSROOT/.repo/deployments/$deployment/usr/lib/modules/$kver/initramfs.img"
    umount -f "$SYSROOT/usr/lib/modules"
}

selinux_policy() {
    local deployment="$1"

    printf "Relabeling deployment %s...\n" "$deployment"
    # podman exec --privileged repo-build \
    #     restorecon -RF "$SYSROOT/boot" || :

    chroot "$SYSROOT/.repo/deployments/$deployment" /usr/bin/env "PATH=/usr/bin" \
        setfiles -F -T"$(nproc)" \
        /etc/selinux/targeted/contexts/files/file_contexts / || :
}

activate_dep() {
    local deployment="$1"
    local cur_dep
    cur_dep="$(cat "$SYSROOT/usr/.repo")" || cur_dep="0"

    if [[ "$deployment" == "$cur_dep" ]]; then
        printf "%s is already activated. Exiting...\n" "$deployment"
        exit 0
    fi

    if [[ -d "$SYSROOT/.repo/empty" ]]; then
        rm -rf "$SYSROOT/.repo/empty/"{*,.*}
    else
        mkdir "$SYSROOT/.repo/empty"
    fi

    if mountpoint -q "$SYSROOT/usr"; then
        mount --make-private "$SYSROOT/"
        mount --make-private "$SYSROOT/usr"
        mount -t overlay usr-root --make-private \
            -o lowerdir="$SYSROOT/.repo/empty:$SYSROOT/.repo/deployments/$deployment/usr" \
            "$SYSROOT/.repo/empty"
        move-mount -mb "$SYSROOT/.repo/empty" "$SYSROOT/usr"
        umount -fl "$SYSROOT/usr"
    else
        mount -t overlay usr-root --make-private \
            -o lowerdir="$SYSROOT/.repo/empty:$SYSROOT/.repo/deployments/$deployment/usr" \
            "$SYSROOT/usr"
    fi

    if mountpoint -q "$SYSROOT/etc"; then
        mount --make-private "$SYSROOT/etc"
        move-mount -db "$SYSROOT/.repo/deployments/$deployment/etc" "$SYSROOT/etc"
        umount -fl "$SYSROOT/etc"
    else
        mount -o bind --make-private "$SYSROOT/.repo/deployments/$deployment/etc" "$SYSROOT/etc"
    fi
}

find_orphans() {
    local op="$1"

    local store_pkgs
    local used_packages
    store_pkgs="$(find "$SYSROOT/.repo/store" -mindepth 1 -maxdepth 1)"
    store_pkgs="$(awk -F"/" '{print $NF}' <<< "$store_pkgs" | sed "s/\.[a-zA-Z-]*$//" | sort -u)"
    used_packages="$(cat "$SYSROOT"/.repo/deployments/*/pkgs)"
    used_packages="$(sort -u <<< "$used_packages")"

    local orphans
    orphans="$(comm -23 <(printf "%s" "$store_pkgs") <(printf "%s" "$used_packages"))"
    if [[ "$op" == "get" ]]; then
        printf "Orphaned packages:\n%s\n" "$(sed 's/^/\t/' <<< "$orphans")"
    elif [[ "$op" == "rm" ]]; then
        printf "Removing orphaned packages:\n%s\n" "$(sed 's/^/\t/' <<< "$orphans")"
        printf "%s" "$orphans" | sed "s/^$SYSROOT/\/.repo\/store\//" | \
        xargs -I{} bash -c "rm -rf {}.repo-lock; rm -rf {}.*"
    fi
}

cleanup_dep() {
    local deployment="$1"
    local cur_dep
    cur_dep="$(cat "$SYSROOT/usr/.repo")"
    if [[ "$deployment" == "$cur_dep" ]]; then
        printf "Not removing currently active deployment...\n"
        return
    fi
    umount -Rfl "$SYSROOT/.repo/deployments/$deployment/"* 2>/dev/null || :
    if [[ -f "$SYSROOT/boot/loader/entries/$deployment.conf" ]]; then
        rm -f "$SYSROOT/boot/loader/entries/$deployment.conf"
    elif [[ -f "$SYSROOT/boot/EFI/Linux/$deployment.efi" ]]; then
        rm -f "$SYSROOT/boot/EFI/Linux/$deployment.efi"
    fi
    if [[ -d "$SYSROOT/boot/$deployment" ]]; then
        rm -rf "$SYSROOT/boot/$deployment"
    fi
    if [[ -d "$SYSROOT/tmp/$deployment" ]]; then
        rm -rf "$SYSROOT/tmp/$deployment"
    fi
    if [[ -d "$SYSROOT/.repo/deployments/$deployment" ]]; then
        rm -rf "$SYSROOT/.repo/deployments/$deployment"
    fi
    if [[ -d "/tmp/$deployment" ]]; then
        rm -rf "/tmp/$deployment"
    fi
    podman stop -t 1 repo-build &>/dev/null
    printf "Cleaned up deployment %s\n" "$deployment"
}

dep() {
    local replace="$1"
    local create="$2"
    local options="$3"

    if [[ "$replace" == "1" ]]; then
        podman create --privileged --name repo-build --replace -ti \
            --volume "$SYSROOT/.repo":/.repo \
            --volume "$SYSROOT/etc/repo/scripts":/scripts \
            --volume /tmp:/tmp \
            "$CONTAINER_IMAGE"
    fi
    podman start repo-build
    if [[ "$replace" == "1" ]]; then
        container_setup
    fi

    if [[ -f "$SYSROOT/etc/repo/scripts/pre.sh" ]]; then
        printf "Running pre script...\n"
        podman exec --privileged repo-build \
            bash /scripts/pre.sh
    fi

    if [[ "$options" =~ update ]]; then
        container_metadata_update
    fi

    declare pkg_list
    pkg_list="$(get_pkg_list "$SYSROOT/etc/repo/list.pkgs")"
    export SYSROOT
    export -f exists_or_install
    export -f dnf_download
    export -f pm_download
    export PACKAGE_MANAGER
    declare pm_transaction
    pm_transaction="$(get_pm_transaction "/empty" "$pkg_list" | tac)"
    populate_store "$pm_transaction"
    export -n SYSROOT
    export -n exists_or_install
    export -n dnf_download
    export -n pm_download
    export -n PACKAGE_MANAGER

    if [[ "$create" == "1" ]]; then
        export SYSROOT
        export -f create_deployment
        export -f get_next_deployment
        export -f get_deployments
        export -f install_packages
        create_deployment "$pm_transaction" "$options"
        export -n SYSROOT
        export -n create_deployment
        export -n get_next_deployment
        export -n get_deployments
        export -n install_packages
    fi

    podman stop -t 1 repo-build &>/dev/null
}

if hash dnf || [[ "$PACKAGE_MANAGER" == "dnf" ]] ; then
    PACKAGE_MANAGER="dnf"
    CONTAINER_IMAGE="${CONTAINER_IMAGE:-quay.io/fedora/fedora-minimal:latest}"
else
    printf "No supported package manager detected. Things might break.\n"
fi

if [[ "$(id -u)" != "0" ]]; then
    case "$SUBCMD" in
        "none")
            printf "No subcommand was specified!\n"
            exit 1
            ;;
        "orphans")
            printf "Finding orphaned paths in the store...\n"
            find_orphans "get"
            ;;
        "status")
            get_dep_stati "$SUBARG"
            ;;
        "diff")
            diff_deps "$SUBARG" "$SUBSUBARG"
            ;;
        *)
            printf "Unknown subcommand.\n\"%s\" might require elevated privileges. Exiting...\n" \
                "$SUBCMD"
            ;;
    esac
else
    case "$SUBCMD" in
        "none")
            printf "No subcommand was specified!\n"
            exit 1
            ;;
        "dep")
            printf "Creating new deployment...\n"
            dep "0" "1" "$SUBARG"
            ;;
        "recreate")
            printf "Recreating build container and rebuilding store...\n"
            dep "1" "0" "$SUBARG"
            ;;
        "orphans")
            printf "Finding orphaned paths in the store...\n"
            find_orphans "get"
            ;;
        "status")
            get_dep_stati "$SUBARG"
            ;;
        "rm")
            printf "Removing dep %s...\n" "$SUBARG"
            cleanup_dep "$SUBARG"
            ;;
        "gc")
            gc_all "$SUBARG"
            ;;
        "diff")
            diff_deps "$SUBARG" "$SUBSUBARG"
            ;;
        "activate")
            printf "Activating deployment %s\n" "$SUBARG"
            activate_dep "$SUBARG"
            ;;
        "init")
            printf "Initiating repo on the host system...\n"
            init_repo
            ;;
        *)
            printf "Unknown subcommand. Exiting...\n"
            ;;
    esac
fi
