#!/usr/bin/env bash
set -oue pipefail

CONTAINER_IMAGE="quay.io/fedora/fedora-minimal:latest"
SUBCMD="${1-none}"
SUBARG="${2-none}"

if [[ "$*" == *"--rootd"* ]]; then
    SYSROOT="${*: -1}"
else
    SYSROOT=""
fi

get_pkg_list() {
    local list="$1"

    printf "%s" "$(cat "$list" | grep -v -e "^#" -e "^\s*$")"
}

get_dnf_transaction() {
    local mockdir="$1"
    local -n pkgs="$2"
    read -ra pkg_array <<< "$(tr "\n" " " <<< "$pkgs")"

    local transaction
    transaction="$(podman exec repo-build \
        dnf install --assumeno --use-host-config --installroot "$mockdir" "${pkg_array[@]}")" || :
    transaction="$(grep "^\s[a-zA-Z0-9].*" <<< "$transaction" | grep -v "^\sInstalling.*")"
    awk '{print $1"@"$3"."$2}' <<< "$transaction"
}

dnf_download() {
    local pkg="$1"
    pkg="$(sed "s/@/-/" <<< "$pkg")"
    podman exec repo-build dnf download --destdir /tmp "$pkg" || :
}

dnf_install() {
    local pkg="$1"
    IFS="@" read -ra pkg_split <<< "$pkg"
    podman exec repo-build bash -c "mkdir -p /.repo/store/$pkg &&
        cd /.repo/store/$pkg &&
        rpm -qp --scripts /tmp/${pkg_split[0]}*.rpm > scripts &&
        rpm2cpio /tmp/${pkg_split[0]}*.rpm | cpio -idm &&
        rm /tmp/${pkg_split[0]}*.rpm &&
        touch /.repo/store/$pkg/.done"
    cd "$SYSROOT/.repo/store/$pkg" &&
        split_scriptlets "$(cat scripts)"
}

split_scriptlets() {
    local scriptlets="$1"
    awk '
        BEGIN {
            header_re = "^[[:alnum:]_+-]+[[:space:]]+scriptlet"
            cur = ""
            fname = ""
        }
        # If line matches header like "postinstall scriptlet (using /bin/sh):"
        $0 ~ header_re {
            # extract first word as section name
            split($0, a, " ")
            cur = a[1]
            fname = cur ".sh"
            print "#!/bin/sh" > fname
            next
        }
        # If within a section, print lines into current file
        {
            if (cur != "") {
                print $0 >> fname
            }
        }
    ' <<< "$scriptlets"
}

exists_or_install() {
    local pkg="$1"

    export SYSROOT
    export -f split_scriptlets
    for _ in {1..3}; do
        if [[ -f "$SYSROOT/.repo/store/$pkg/.done" ]]; then
            printf "%s found in store\n" "$pkg"
            break
        else
            dnf_download "$pkg"
            dnf_install "$pkg"
        fi
    done
    export -n SYSROOT
    export -n split_scriptlets
}

run_package_scripts() {
    local deployment="$1"
    local pkg="$2"
    printf "Running %s scripts...\n" "$pkg"
    cd "$SYSROOT/.repo/store/$pkg"
    for script in *.sh; do
        case "$script" in
            preinstall.sh)
                arg1=1
                ;;
            postinstall.sh)
                arg1=1
                ;;
            posttrans.sh)
                arg1=2
                ;;
            *)
                continue
                ;;
        esac
        cp "$script" "$SYSROOT/.repo/deployments/$deployment/$script"
        chroot "$SYSROOT/.repo/deployments/$deployment" \
            /usr/bin/env PATH="/usr/bin" bash "/$script" "$arg1"
        rm "$SYSROOT/.repo/deployments/$deployment/$script"
    done
}

populate_store() {
    local dnf_transaction="$1"
    local store_pkgs="$2"
    printf "%s" "$dnf_transaction" | xargs -P"$(nproc)" -I{} \
        bash -c 'exists_or_install "$@"' _ {}
}

get_deployments() {
    printf "%s" "$(find "$SYSROOT/.repo/deployments" -mindepth 1 -maxdepth 1 -regex ".*/[0-9]+" | \
        awk -F"/" '{print $NF}')"
}

get_next_deployment() {
    local deployments
    deployments="$(get_deployments)"
    if [[ "$deployments" == "" ]]; then
        printf "0"
    else
        printf "%s" "$(($(sort -rn <<< "$deployments" | head -n1)+1))"
    fi
}

create_deployment() {
    local dnf_transaction="$1"
    local drop="$2"
    local next_dep
    next_dep="$(get_next_deployment)"
    mkdir -p "$SYSROOT/.repo/deployments/$next_dep/usr/lib"
    mkdir -p "$SYSROOT/.repo/deployments/$next_dep/etc"
    printf "%s" "$dnf_transaction" > "$SYSROOT/.repo/deployments/$next_dep/pkgs"
    printf "%s" "$next_dep" > "$SYSROOT/.repo/deployments/$next_dep/usr/.repo"
    mkdir "$SYSROOT/boot/$next_dep"

    mkdir -p "$SYSROOT/.repo/deployments/$next_dep/"{dev,proc,run,sys,tmp}
    mount -t proc /proc "$SYSROOT/.repo/deployments/$next_dep/proc/"
    mount -t sysfs /sys "$SYSROOT/.repo/deployments/$next_dep/sys/"
    mount -t tmpfs tmpfs "$SYSROOT/.repo/deployments/$next_dep/tmp/"
    mount --bind /dev "$SYSROOT/.repo/deployments/$next_dep/dev/"
    mount --bind /run "$SYSROOT/.repo/deployments/$next_dep/run/"
    mount --bind /sys/firmware/efi/efivars "$SYSROOT/.repo/deployments/$next_dep/sys/firmware/efi/efivars/"

    export next_dep
    printf "%s" "$dnf_transaction" | xargs -P"$(nproc)" -I{} \
        bash -c 'install_package "$next_dep" "$@"' _ {} || :

    ln -s usr/lib "$SYSROOT/.repo/deployments/$next_dep/lib"
    ln -s usr/lib64 "$SYSROOT/.repo/deployments/$next_dep/lib64"
    ln -s usr/bin "$SYSROOT/.repo/deployments/$next_dep/bin"
    ln -s usr/sbin "$SYSROOT/.repo/deployments/$next_dep/sbin"
    ln -s bin "$SYSROOT/.repo/deployments/$next_dep/usr/sbin"
    cp "$SYSROOT/etc/repo/scripts/post.sh" "$SYSROOT/.repo/deployments/$next_dep/post.sh"

    mkdir -p "$SYSROOT/.repo/deployments/$next_dep/var/"{cache,lib,log}
    printf "%s" "$dnf_transaction" | xargs -I{} \
        bash -c 'run_package_scripts "$next_dep" "$@"' _ {} || :

    install_repo "$next_dep"

    printf "Running post script...\n"
    if [[ -f "$SYSROOT/etc/repo/scripts/post.sh" ]]; then
        cp "$SYSROOT/etc/repo/scripts/post.sh" "$SYSROOT/.repo/deployments/$next_dep/post.sh"
        chroot "$SYSROOT/.repo/deployments/$next_dep" \
            /usr/bin/env "PATH=/usr/bin" bash /post.sh
    fi

    system_config "$next_dep" "$drop"

    boot_files "$next_dep"

    selinux_policy "$next_dep"

    umount -Rf "$SYSROOT/.repo/deployments/$next_dep/"* || :
}

system_config() {
    local deployment="$1"
    local drop="$2"

    printf "Syncing system config...\n"
    find "$SYSROOT/.repo/deployments/$deployment/etc" -mindepth 1 -execdir sh -c "touch -d @0 '{}' &>/dev/null || :" \;

    if [[ "$drop" != "drop" ]]; then
        find "$SYSROOT/etc" -newermt @0 -print0 2>/dev/null | xargs -0 -I{} cp -fa --parents {} "$SYSROOT/.repo/deployments/$deployment/" || :
    fi

    cp -rfa --parents "$SYSROOT/etc/fstab" "$SYSROOT/etc/crypttab" "$SYSROOT/etc/locale.conf" \
        "$SYSROOT/etc/localtime" "$SYSROOT/etc/adjtime" "$SYSROOT/etc/sudoers.d" \
        "$SYSROOT/etc/group" "$SYSROOT/etc/gshadow" "$SYSROOT/etc/subgid" "$SYSROOT/etc/subuid" \
        "$SYSROOT/etc/NetworkManager/system-connections" "$SYSROOT/etc/vconsole.conf" \
        "$SYSROOT/etc/pki" "$SYSROOT/etc/firewalld" "$SYSROOT/etc/environment" \
        "$SYSROOT/etc/hostname" "$SYSROOT/etc/X11/xorg.conf.d/00-keyboard.conf" \
        "$SYSROOT/etc/sudoers" "$SYSROOT/etc/ald" \
        "$SYSROOT/.repo/deployments/$deployment/" 2>/dev/null || :

    sort "$SYSROOT/etc/passwd" "$SYSROOT/.repo/deployments/$deployment/etc/passwd" | awk -F':' '!a[$1]++' > "$SYSROOT/.repo/deployments/$deployment/etc/passwd.tmp" &&
        mv "$SYSROOT/.repo/deployments/$deployment/etc/passwd.tmp" "$SYSROOT/.repo/deployments/$deployment/etc/passwd"
    sort "$SYSROOT/etc/shadow" "$SYSROOT/.repo/deployments/$deployment/etc/shadow" | awk -F':' '!a[$1]++' > "$SYSROOT/.repo/deployments/$deployment/etc/shadow.tmp" &&
        mv "$SYSROOT/.repo/deployments/$deployment/etc/shadow.tmp" "$SYSROOT/.repo/deployments/$deployment/etc/shadow"
    sort "$SYSROOT/etc/group" "$SYSROOT/.repo/deployments/$deployment/etc/group" | awk -F':' '!a[$1]++' > "$SYSROOT/.repo/deployments/$deployment/etc/group.tmp" &&
        mv "$SYSROOT/.repo/deployments/$deployment/etc/group.tmp" "$SYSROOT/.repo/deployments/$deployment/etc/group"
}

boot_files() {
    local deployment="$1"

    printf "Placing kernel and initramfs...\n"
    kernel="$(find "$SYSROOT/.repo/deployments/$deployment/usr/lib/modules" -name vmlinuz | sort | tail -n1)"
    initrd="$(find "$SYSROOT/.repo/deployments/$deployment/usr/lib/modules" -name initramfs.img | sort | tail -n1)"

    cp -fa "$kernel" "$SYSROOT/boot/$deployment/vmlinuz"
    cp -fa "$initrd" "$SYSROOT/boot/$deployment/initramfs.img"

    printf "Creating boot entry...\n"
    cat "$SYSROOT/etc/repo/boot.conf" | sed "s/INSERT_DEPLOYMENT/$deployment/g" > "$SYSROOT/boot/loader/entries/$deployment.conf"
}

install_repo() {
    local deployment="$1"
    podman create --replace --pull newer --name repo-tmp ghcr.io/nostale3210/repo-utils:latest
    podman cp repo-tmp:/app/repo "$SYSROOT/.repo/deployments/$deployment/usr/bin/repo"
    podman cp repo-tmp:/app/move-mount "$SYSROOT/.repo/deployments/$deployment/usr/bin/move-mount"
    podman cp repo-tmp:/app/init/90repo "$SYSROOT/.repo/deployments/$deployment/usr/lib/dracut/modules.d/90repo"
    podman cp repo-tmp:/app/init/repo-boot.service "$SYSROOT/.repo/deployments/$deployment/usr/lib/systemd/system/repo-boot.service"
    podman cp repo-tmp:/app/init/repo-boot.sh "$SYSROOT/.repo/deployments/$deployment/usr/libexec/repo-boot.sh"
    chmod +x "$SYSROOT/.repo/deployments/$deployment/usr/libexec/repo-boot.sh"
    podman rm repo-tmp
}

init_repo() {
    podman create --replace --pull newer --name repo-tmp ghcr.io/nostale3210/repo-utils:latest

    podman cp repo-tmp:/app/repo "$SYSROOT/usr/bin/repo"
    podman cp repo-tmp:/app/move-mount "$SYSROOT/usr/bin/move-mount"
    podman cp repo-tmp:/app/init/90repo "$SYSROOT/usr/lib/dracut/modules.d/90repo"
    podman cp repo-tmp:/app/init/repo-boot.service "$SYSROOT/usr/lib/systemd/system/repo-boot.service"
    podman cp repo-tmp:/app/init/repo-boot.sh "$SYSROOT/usr/libexec/repo-boot.sh"
    chmod +x "$SYSROOT/usr/libexec/repo-boot.sh"

    mkdir -p "$SYSROOT/.repo/"{store,deployments/0}
    mkdir -p "$SYSROOT/etc/repo"
    podman cp repo-tmp:/app/list.pkgs "$SYSROOT/etc/repo/list.pkgs"
    podman cp repo-tmp:/app/scripts "$SYSROOT/etc/repo/scripts"

    podman rm repo-tmp
}

install_package() {
    local deployment="$1"
    local pkg="$2"
    local pkg_dirs
    local pkg_files
    printf "Installing %s\n" "$pkg"
    rsync -aHlx --link-dest="../../../store/$pkg/usr/" \
        "$SYSROOT/.repo/store/$pkg/usr/" \
        "$SYSROOT/.repo/deployments/$deployment/usr/" &>/dev/null
    rsync -aHlx --link-dest="../../../../store/$pkg/lib/" \
        "$SYSROOT/.repo/store/$pkg/lib/" \
        "$SYSROOT/.repo/deployments/$deployment/usr/lib/" &>/dev/null
    rsync -aHlx --link-dest="../../../../store/$pkg/lib64/" \
        "$SYSROOT/.repo/store/$pkg/lib64/" \
        "$SYSROOT/.repo/deployments/$deployment/usr/lib64/" &>/dev/null
    rsync -aHlx "$SYSROOT/.repo/store/$pkg/etc/" "$SYSROOT/.repo/deployments/$deployment/etc/" &>/dev/null
}

selinux_policy() {
    local deployment="$1"

    printf "Relabeling deployment %s...\n" "$deployment"
    # podman exec repo-build \
    #     restorecon -RF "$SYSROOT/boot" || :

    chroot "$SYSROOT/.repo/deployments/$deployment" /usr/bin/env "PATH=/usr/bin" \
        setfiles -F -T"$(nproc)" \
        /etc/selinux/targeted/contexts/files/file_contexts / || :
}

activate_dep() {
    local deployment="$1"
    local cur_dep
    cur_dep="$(cat "$SYSROOT/usr/.repo")"

    if [[ "$deployment" == "$cur_dep" ]]; then
        printf "%s is already activated. Exiting...\n" "$deployment"
        exit 0
    fi

    if [[ -d "$SYSROOT/.repo/empty" ]]; then
        rm -rf "$SYSROOT/.repo/empty/"{*,.*}
    else
        mkdir "$SYSROOT/.repo/empty"
    fi

    if mountpoint -q "$SYSROOT/usr"; then
        mount --make-private "$SYSROOT/"
        mount --make-private "$SYSROOT/usr"
        mount -t overlay usr-root --make-private \
            -o lowerdir="$SYSROOT/.repo/empty:$SYSROOT/.repo/deployments/$deployment/usr" \
            "$SYSROOT/.repo/empty"
        move-mount -mb "$SYSROOT/.repo/empty" "$SYSROOT/usr"
        umount -fl "$SYSROOT/usr"
    else
        mount -t overlay usr-root --make-private \
            -o lowerdir="$SYSROOT/.repo/empty:$SYSROOT/.repo/deployments/$deployment/usr" \
            "$SYSROOT/usr"
    fi

    if mountpoint -q "$SYSROOT/etc"; then
        mount --make-private "$SYSROOT/etc"
        move-mount -db "$SYSROOT/.repo/deployments/$deployment/etc" "$SYSROOT/etc"
        umount -fl "$SYSROOT/etc"
    else
        mount -o bind --make-private "$SYSROOT/.repo/deployments/$deployment/etc" "$SYSROOT/etc"
    fi
}

find_orphans() {
    local op="$1"
    podman start repo-build

    declare store_pkgs
    local used_packages
    store_pkgs="$(podman exec repo-build \
        find /.repo/store -mindepth 1 -maxdepth 1)"
    store_pkgs="$(awk -F"/" '{print $NF}' <<< "$store_pkgs" | sort)"
    used_packages="$(podman exec repo-build bash -c 'cat /.repo/deployments/*/pkgs')"
    used_packages="$(sort -u <<< "$used_packages")"
    local orphans
    orphans="$(comm -23 <(printf "%s" "$store_pkgs") <(printf "%s" "$used_packages"))"
    if [[ "$op" == "get" ]]; then
        printf "%s\n" "$orphans"
    elif [[ "$op" == "rm" ]]; then
        printf "%s" "$orphans" | sed "s/^/\/.repo\/store\//" | xargs podman exec repo-build \
            rm -rf
    fi

    podman stop -t 2 repo-build &>/dev/null
}

dep() {
    local replace="$1"
    local update="$2"
    local create="$3"
    local drop="$4"

    if [[ "$replace" == "1" ]]; then
        podman create --name repo-build --replace -ti \
            --volume "$SYSROOT/.repo":/.repo:Z \
            --volume "$SYSROOT/etc/repo/scripts":/scripts:Z \
            "$CONTAINER_IMAGE"
    fi
    podman start repo-build
    if [[ "$replace" == "1" ]]; then
        podman exec repo-build dnf install -y cpio policycoreutils
    fi
    if [[ "$update" == "1" && "$replace" == "0" ]]; then
        podman exec repo-build dnf check-upgrade --refresh -y
    fi

    if [[ -f "$SYSROOT/etc/repo/scripts/pre.sh" ]]; then
        printf "Running pre script...\n"
        podman exec repo-build \
            bash /scripts/pre.sh
    fi

    declare pkg_list
    pkg_list="$(get_pkg_list "$SYSROOT/etc/repo/list.pkgs")"
    declare store_pkgs
    store_pkgs="$(podman exec repo-build \
        find /.repo/store -mindepth 1 -maxdepth 1)"
    export store_pkgs
    export SYSROOT
    export -f exists_or_install
    export -f dnf_download
    export -f dnf_install
    export -f split_scriptlets
    declare dnf_transaction
    dnf_transaction="$(get_dnf_transaction "/empty" pkg_list | tac)"
    populate_store "$dnf_transaction" "$store_pkgs"
    export -n SYSROOT
    export -n store_pkgs
    export -n exists_or_install
    export -n dnf_download
    export -n dnf_install
    export -n split_scriptlets

    if [[ "$create" == "1" ]]; then
        export SYSROOT
        export -f create_deployment
        export -f get_next_deployment
        export -f get_deployments
        export -f install_package
        export -f split_scriptlets
        export -f run_package_scripts
        create_deployment "$dnf_transaction" "$drop"
        export -n SYSROOT
        export -n create_deployment
        export -n get_next_deployment
        export -n get_deployments
        export -n install_package
        export -n split_scriptlets
        export -n run_package_scripts
    fi

    podman stop -t 2 repo-build &>/dev/null
}

case "$SUBCMD" in
    "none")
        printf "No subcommand was specified!\n"
        exit 1
        ;;
    "dep")
        printf "Creating new deployment...\n"
        dep "0" "0" "1" "$SUBARG"
        ;;
    "update")
        printf "Updating store and creating new deployment...\n"
        dep "0" "1" "1"
        ;;
    "recreate")
        printf "Recreating build container and rebuilding store...\n"
        dep "1" "0" "0"
        ;;
    "get-orphans")
        printf "Finding orphaned paths in the store...\n"
        find_orphans "get"
        ;;
    "gc")
        printf "Removing unused store paths...\n"
        find_orphans "rm"
        ;;
    "activate")
        printf "Activating deployment %s\n" "$SUBARG"
        activate_dep "$SUBARG"
        ;;
    "init")
        printf "Initiating repo on the host system...\n"
        init_repo
        ;;
esac
