#!/usr/bin/env bash
set -oueE pipefail

CONTAINER_IMAGE="quay.io/fedora/fedora-minimal:latest"
REPO_IMAGE="ghcr.io/nostale3210/repo-utils:latest"
MAX_DEPS="4"
SUBCMD="${1-none}"
SUBARG="${2-none}"
SUBSUBARG="${3-none}"

if [[ "$*" == *"--rootd"* ]]; then
    SYSROOT="${*: -1}"
else
    SYSROOT=""
fi

get_pkg_list() {
    local list="$1"

    printf "%s" "$(cat "$list" | grep -v -e "^#" -e "^\s*$")"
}

get_dnf_transaction() {
    local mockdir="$1"
    local -n pkgs="$2"
    read -ra pkg_array <<< "$(tr "\n" " " <<< "$pkgs")"

    local transaction
    transaction="$(podman exec --privileged repo-build \
        dnf install --assumeno --use-host-config --installroot "$mockdir" "${pkg_array[@]}")" || :
    transaction="$(grep "^\s[a-zA-Z0-9].*" <<< "$transaction" | grep -v "^\sInstalling.*")"
    awk '$5 ~ /.+/' <<< "$transaction" | awk '{print $1"@"$3"."$2}'
}

dnf_download() {
    local pkg="$1"
    local pkg_name="$2"
    podman exec --privileged repo-build bash -c "dnf download -y --destdir /tmp ${pkg//@/-}
    mv -f /tmp/$pkg_name*.rpm /.repo/store/$pkg.rpm"
}

exists_or_install() {
    local pkg="$1"
    IFS="@" read -ra pkg_split <<< "$pkg"

    export SYSROOT
    for i in {0..3}; do
        if [[ -f "$SYSROOT/.repo/store/$pkg.rpm" ]]; then
            printf "%s found in store\n" "$pkg"
            break
        else
            if [[ "$i" == "3" ]]; then
                printf "%s (%s) couldn't be downloaded\n" "$pkg" "${pkg_split[0]}"
                exit 255;
            fi
            sleep "$((i*3))"
            dnf_download "$pkg" "${pkg_split[0]}"
        fi
    done
    export -n SYSROOT
}

populate_store() {
    local dnf_transaction="$1"
    printf "%s" "$dnf_transaction" | xargs -P"$(nproc)" -I{} \
        bash -c 'exists_or_install "$@"' _ {} ||
        { printf "Couldn't install some packages. Exiting...\n"; exit 1; }
}

get_deployments() {
    printf "%s" "$(find "$SYSROOT/.repo/deployments" -mindepth 1 -maxdepth 1 -regex ".*/[0-9]+" | \
        awk -F"/" '{print $NF}')"
}

get_all_deployments() {
    in_boot="$(find "$SYSROOT/boot" -mindepth 1 -maxdepth 1 -type d -printf "%f\n" 2>/dev/null | \
        grep "^[0-9]*$")" || :
    in_entries="$(find "$SYSROOT/boot/loader/entries" -mindepth 1 -maxdepth 1 -type f -printf "%f\n" 2>/dev/null | \
        grep "^[0-9]*.conf$" | \
        sed "s/.conf$//")" || :
    in_ukis="$(find "$SYSROOT/boot/EFI/Linux" -mindepth 1 -maxdepth 1 -type f -printf "%f\n" 2>/dev/null | \
        grep "^[0-9]*.efi$" | \
        sed "s/.efi$//")" || :
    in_deps="$(find "$SYSROOT/.repo/deployments" -mindepth 1 -maxdepth 1 -type d -printf "%f\n" 2>/dev/null | \
        grep "^[0-9]*$")" || :
    printf "%s\n%s\n%s\n%s\n" "$in_boot" "$in_entries" "$in_ukis" "$in_deps" |
        grep -v "^\s*$" |
        sort -u
}

get_dep_intact() {
    local deployment="$1"
    local boot
    local dep
    if [[ -d "$SYSROOT/boot/$deployment" && -f "$SYSROOT/boot/loader/entries/$deployment.conf" ]]; then
        boot="1"
    else
        boot="0"
    fi
    if [[ -f "$SYSROOT/boot/EFI/Linux/$deployment.efi" && "$boot" == "0" ]]; then
        boot="1"
    fi
    if [[ -d "$SYSROOT/.repo/deployments/$deployment" ]]; then
        dep="1"
    else
        dep="0"
    fi
    if [[ "$boot" == "1" && "$dep" == "1" ]]; then
        printf "1"
    else
        printf "0"
    fi
}

get_dep_status() {
    local deployment="$1"
    local intact
    intact="$(get_dep_intact "$deployment")"
    if [[ "$intact" == "0" ]]; then
        printf "Deployment %s:\n\tdefective\n" "$deployment"
    else
        local kernel
        local created
        kernel="$(ls "$SYSROOT/.repo/deployments/$deployment/usr/lib/modules")"
        created="$(stat --printf "%y" "$SYSROOT/.repo/deployments/$deployment")"
        printf "Deployment %s:\n\tKernel: %s\n\tCreated: %s\n" "$deployment" "$kernel" "$created"
    fi
}

get_dep_stati() {
    local deployment="$1"
    if [[ "$deployment" == "none" || "$deployment" == "--rootd" ]]; then
        export -f get_dep_status
        export -f get_dep_intact
        export SYSROOT
        printf "\n"
        get_all_deployments | xargs -I{} bash -c "get_dep_status {} && printf '\n'"
        export -n get_dep_status
        export -n get_dep_intact
        export -n SYSROOT
    else
        get_dep_status "$1"
    fi
}

gc_defective() {
    local all_deps
    all_deps="$(get_all_deployments)"
    read -ra all_deps_arr <<< "$(printf "%s\n" "$all_deps" | tr "\n" " ")"
    for dep in "${all_deps_arr[@]}"; do
        local intact
        intact="$(get_dep_intact "$dep")"
        if [[ "$intact" == "0" ]]; then
            cleanup_dep "$dep" 2>/dev/null
        fi
    done
}

gc_all() {
    printf "Finding orphans in store...\n"
    find_orphans "rm"
    printf "Collecting broken deployments...\n"
    gc_defective

    local current_deps
    local current_deps_num
    current_deps="$(get_all_deployments)"
    current_deps_num="$(wc -l <<< "$current_deps")"
    while [[ "$current_deps_num" -gt "$MAX_DEPS" ]]; do
        local dep
        dep="$(head -n1 <<< "$current_deps")"
        printf "Collecting deployment %s...\n" "$dep"
        cleanup_dep "$dep" 2>/dev/null
        current_deps="$(get_all_deployments)"
        current_deps_num="$(wc -l <<< "$current_deps")"
    done
}

diff_deps() {
    local dep1="$1"
    local dep2="$2"

    if [[ "$dep1" == "none" || "$dep2" == "none" ]]; then
        printf "This command needs two deployments. Exiting...\n"
    fi

    diff -y "$SYSROOT/.repo/deployments/$dep1/pkgs" "$SYSROOT/.repo/deployments/$dep2/pkgs" |
        grep "<\||\|>"
}

get_next_deployment() {
    local deployments
    deployments="$(get_deployments)"
    if [[ "$deployments" == "" ]]; then
        printf "0"
    else
        printf "%s" "$(($(sort -rn <<< "$deployments" | head -n1)+1))"
    fi
}

create_deployment() {
    local dnf_transaction="$1"
    local drop="$2"
    local prev_dep
    local next_dep
    next_dep="$(get_next_deployment)"
    prev_dep="$((next_dep-1))"

    trap 'cleanup_dep "$next_dep" 2>/dev/null' INT TERM ERR

    printf "Creating deployment %s...\n" "$next_dep"

    podman exec --privileged repo-build bash -c "mkdir -p /tmp/$next_dep/{usr,etc}"

    export next_dep
    install_package "$next_dep" "$dnf_transaction" :

    podman exec --privileged repo-build cp /scripts/post.sh "/tmp/$next_dep/post.sh"

    install_repo "$next_dep"

    if [[ "$next_dep" == "0" || "$prev_dep" == "0" ]]; then
        mv -f "/tmp/$next_dep" "$SYSROOT/.repo/deployments/$next_dep"
    else
        mkdir -p "$SYSROOT/.repo/deployments/$next_dep/"{usr,etc}
        printf "Hardlinking previous deployment...\n"
        rsync -aHlx --link-dest="../../$prev_dep/usr/" "$SYSROOT/.repo/deployments/$prev_dep/usr/" "$SYSROOT/.repo/deployments/$next_dep/usr/"
        printf "Syncing previous config...\n"
        rsync -aHlx "$SYSROOT/.repo/deployments/$prev_dep/etc/" "$SYSROOT/.repo/deployments/$next_dep/etc/"
        printf "Syncing next directory skeleton...\n"
        rsync -ac -f"+ */" -f"- *" --delete "/tmp/$next_dep/" "$SYSROOT/.repo/deployments/$next_dep/"
        printf "Syncing next deployment to disk...\n"
        find "/tmp/$next_dep" -not -type d -printf "%s\t%p\n" |
            sort -nr | cut -f2- | sed "s/^\(\/tmp\/$next_dep\)/\1\/./g" |
            grep -e "^/tmp/$next_dep/\./usr" -e "^/tmp/$next_dep/\./etc" \
            -e "^/tmp/$next_dep/\./bin" -e "^/tmp/$next_dep/\./sbin" \
            -e "^/tmp/$next_dep/\./lib" -e "^/tmp/$next_dep/\./lib64" |
            xargs -n5000 -P"$(nproc)" \
            bash -c 'sysroot="$0" && shift && rsync -aHlcx --delete --relative --ignore-missing-args "$@" "$sysroot/.repo/deployments/$next_dep/"' "$SYSROOT" _
        printf "Trimming image...\n"
        local dirty
        local clean
        dirty="$(find "$SYSROOT/.repo/deployments/$next_dep/usr" "$SYSROOT/.repo/deployments/$next_dep/etc" | sed "s|^$SYSROOT/.repo/deployments/$next_dep||g" | sort)"
        clean="$(find "/tmp/$next_dep/usr" "/tmp/$next_dep/etc" | sed "s/^\/tmp\/$next_dep//g" | sort)"
        comm -23 <(printf "%s" "$dirty") <(printf "%s" "$clean") |
            sed "s|^|$SYSROOT/.repo/deployments/$next_dep|g" | xargs rm -rf
    fi

    rm -rf "/tmp/$next_dep"

    mkdir -p "$SYSROOT/.repo/deployments/$next_dep/"{dev,proc,run,sys,tmp}
    mount -t proc /proc "$SYSROOT/.repo/deployments/$next_dep/proc/"
    mount -t sysfs /sys "$SYSROOT/.repo/deployments/$next_dep/sys/"
    mount -t tmpfs tmpfs "$SYSROOT/.repo/deployments/$next_dep/tmp/"
    mount --bind /dev "$SYSROOT/.repo/deployments/$next_dep/dev/"
    mount --bind /run "$SYSROOT/.repo/deployments/$next_dep/run/"
    mount --bind /sys/firmware/efi/efivars "$SYSROOT/.repo/deployments/$next_dep/sys/firmware/efi/efivars/"

    printf "Running post script...\n"
    if [[ -f "$SYSROOT/etc/repo/scripts/post.sh" ]]; then
        cp "$SYSROOT/etc/repo/scripts/post.sh" "$SYSROOT/.repo/deployments/$next_dep/post.sh"
        chroot "$SYSROOT/.repo/deployments/$next_dep" \
            /usr/bin/env "PATH=/usr/bin" bash /post.sh
    fi

    system_config "$next_dep" "$drop"

    mkdir "$SYSROOT/boot/$next_dep"
    boot_files "$next_dep"

    selinux_policy "$next_dep"

    umount -Rfl "$SYSROOT/.repo/deployments/$next_dep/"* 2>/dev/null || :

    printf "%s" "$dnf_transaction" > "$SYSROOT/.repo/deployments/$next_dep/pkgs"
    printf "%s" "$next_dep" > "$SYSROOT/.repo/deployments/$next_dep/usr/.repo"

    export -n next_dep
}

system_config() {
    local deployment="$1"
    local drop="$2"

    printf "Syncing system config...\n"
    find "$SYSROOT/.repo/deployments/$deployment/etc" -mindepth 1 -execdir sh -c "touch -d @0 '{}' &>/dev/null || :" \;

    if [[ "$drop" != "drop" ]]; then
        find "$SYSROOT/etc" -newermt @0 -print0 2>/dev/null | xargs -0 -I{} cp -fa --parents {} "$SYSROOT/.repo/deployments/$deployment/" || :
    fi

    cp -rfa --parents "$SYSROOT/etc/fstab" "$SYSROOT/etc/crypttab" "$SYSROOT/etc/locale.conf" \
        "$SYSROOT/etc/localtime" "$SYSROOT/etc/adjtime" "$SYSROOT/etc/sudoers.d" \
        "$SYSROOT/etc/group" "$SYSROOT/etc/gshadow" "$SYSROOT/etc/subgid" "$SYSROOT/etc/subuid" \
        "$SYSROOT/etc/NetworkManager/system-connections" "$SYSROOT/etc/vconsole.conf" \
        "$SYSROOT/etc/pki" "$SYSROOT/etc/firewalld" "$SYSROOT/etc/environment" \
        "$SYSROOT/etc/hostname" "$SYSROOT/etc/X11/xorg.conf.d/00-keyboard.conf" \
        "$SYSROOT/etc/sudoers" "$SYSROOT/etc/repo" \
        "$SYSROOT/.repo/deployments/$deployment/" 2>/dev/null || :

    sort "$SYSROOT/etc/passwd" "$SYSROOT/.repo/deployments/$deployment/etc/passwd" | awk -F':' '!a[$1]++' > "$SYSROOT/.repo/deployments/$deployment/etc/passwd.tmp" &&
        mv "$SYSROOT/.repo/deployments/$deployment/etc/passwd.tmp" "$SYSROOT/.repo/deployments/$deployment/etc/passwd"
    sort "$SYSROOT/etc/shadow" "$SYSROOT/.repo/deployments/$deployment/etc/shadow" | awk -F':' '!a[$1]++' > "$SYSROOT/.repo/deployments/$deployment/etc/shadow.tmp" &&
        mv "$SYSROOT/.repo/deployments/$deployment/etc/shadow.tmp" "$SYSROOT/.repo/deployments/$deployment/etc/shadow"
    sort "$SYSROOT/etc/group" "$SYSROOT/.repo/deployments/$deployment/etc/group" | awk -F':' '!a[$1]++' > "$SYSROOT/.repo/deployments/$deployment/etc/group.tmp" &&
        mv "$SYSROOT/.repo/deployments/$deployment/etc/group.tmp" "$SYSROOT/.repo/deployments/$deployment/etc/group"
}

boot_files() {
    local deployment="$1"

    printf "Placing kernel and initramfs...\n"
    kernel="$(find "$SYSROOT/.repo/deployments/$deployment/usr/lib/modules" -name vmlinuz | sort | tail -n1)"
    initrd="$(find "$SYSROOT/.repo/deployments/$deployment/usr/lib/modules" -name initramfs.img | sort | tail -n1)"

    local boot_type
    if hash ukify; then
        local cmdline
        boot_type="uki"
        cmdline="$(cat "$SYSROOT/etc/repo/boot.conf" | \
            grep "^options " | \
            sed "s/^options //" | \
            sed "s/INSERT_DEPLOYMENT/$deployment/g")"
        ukify build --linux="$kernel" --initrd="$initrd" \
            --cmdline="$cmdline" --output="$SYSROOT/boot/EFI/Linux/$deployment.efi"
    else
        boot_type="default"
        cp -fa "$kernel" "$SYSROOT/boot/$deployment/vmlinuz"
        cp -fa "$initrd" "$SYSROOT/boot/$deployment/initramfs.img"
    fi

    if hash sbctl && [[ -d "$SYSROOT/var/lib/sbctl" ]]; then
        if [[ "$boot_type" == "uki" ]]; then
            sbctl sign "$SYSROOT/boot/EFI/Linux/$deployment.efi"
        else
            sbctl sign "$SYSROOT/boot/$deployment/vmlinuz"
        fi
    fi

    printf "Creating boot entry...\n"
    cat "$SYSROOT/etc/repo/boot.conf" | sed "s/INSERT_DEPLOYMENT/$deployment/g" > "$SYSROOT/boot/loader/entries/$deployment.conf"
}

install_repo() {
    local deployment="$1"
    podman create --privileged --replace --pull newer --name repo-tmp "$REPO_IMAGE"
    podman cp repo-tmp:/app/repo "/tmp/$deployment/usr/bin/repo"
    podman cp repo-tmp:/app/move-mount "/tmp/$deployment/usr/bin/move-mount"
    podman cp repo-tmp:/app/init/90repo "/tmp/$deployment/usr/lib/dracut/modules.d/90repo"
    podman cp repo-tmp:/app/init/repo-boot.service "/tmp/$deployment/usr/lib/systemd/system/repo-boot.service"
    podman cp repo-tmp:/app/init/repo-boot.sh "/tmp/$deployment/usr/libexec/repo-boot.sh"
    chmod +x "/tmp/$deployment/usr/libexec/repo-boot.sh"
    podman rm repo-tmp
}

init_repo() {
    podman create --privileged --replace --pull newer --name repo-tmp "$REPO_IMAGE"

    podman cp repo-tmp:/app/repo "$SYSROOT/usr/bin/repo"
    podman cp repo-tmp:/app/move-mount "$SYSROOT/usr/bin/move-mount"
    podman cp repo-tmp:/app/init/90repo "$SYSROOT/usr/lib/dracut/modules.d/90repo"
    podman cp repo-tmp:/app/init/repo-boot.service "$SYSROOT/usr/lib/systemd/system/repo-boot.service"
    podman cp repo-tmp:/app/init/repo-boot.sh "$SYSROOT/usr/libexec/repo-boot.sh"
    chmod +x "$SYSROOT/usr/libexec/repo-boot.sh"

    mkdir -p "$SYSROOT/.repo/"{store,deployments/0}
    mkdir -p "$SYSROOT/etc/repo"
    podman cp repo-tmp:/app/list.pkgs "$SYSROOT/etc/repo/list.pkgs"
    podman cp repo-tmp:/app/scripts "$SYSROOT/etc/repo/scripts"

    podman rm repo-tmp
}

install_package() {
    local deployment="$1"
    local dnf_transaction
    dnf_transaction="$(sed "s/\(.*\)$/\/.repo\/store\/\1.rpm/" <<< "$2")"
    read -ra pkg_array <<< "$(tr "\n" " " <<< "$dnf_transaction")"
    podman exec --privileged repo-build dnf install -y --installroot="/tmp/$deployment" "${pkg_array[@]}" || :
}

selinux_policy() {
    local deployment="$1"

    printf "Relabeling deployment %s...\n" "$deployment"
    # podman exec --privileged repo-build \
    #     restorecon -RF "$SYSROOT/boot" || :

    chroot "$SYSROOT/.repo/deployments/$deployment" /usr/bin/env "PATH=/usr/bin" \
        setfiles -F -T"$(nproc)" \
        /etc/selinux/targeted/contexts/files/file_contexts / || :
}

activate_dep() {
    local deployment="$1"
    local cur_dep
    cur_dep="$(cat "$SYSROOT/usr/.repo")" || cur_dep="0"

    if [[ "$deployment" == "$cur_dep" ]]; then
        printf "%s is already activated. Exiting...\n" "$deployment"
        exit 0
    fi

    if [[ -d "$SYSROOT/.repo/empty" ]]; then
        rm -rf "$SYSROOT/.repo/empty/"{*,.*}
    else
        mkdir "$SYSROOT/.repo/empty"
    fi

    if mountpoint -q "$SYSROOT/usr"; then
        mount --make-private "$SYSROOT/"
        mount --make-private "$SYSROOT/usr"
        mount -t overlay usr-root --make-private \
            -o lowerdir="$SYSROOT/.repo/empty:$SYSROOT/.repo/deployments/$deployment/usr" \
            "$SYSROOT/.repo/empty"
        move-mount -mb "$SYSROOT/.repo/empty" "$SYSROOT/usr"
        umount -fl "$SYSROOT/usr"
    else
        mount -t overlay usr-root --make-private \
            -o lowerdir="$SYSROOT/.repo/empty:$SYSROOT/.repo/deployments/$deployment/usr" \
            "$SYSROOT/usr"
    fi

    if mountpoint -q "$SYSROOT/etc"; then
        mount --make-private "$SYSROOT/etc"
        move-mount -db "$SYSROOT/.repo/deployments/$deployment/etc" "$SYSROOT/etc"
        umount -fl "$SYSROOT/etc"
    else
        mount -o bind --make-private "$SYSROOT/.repo/deployments/$deployment/etc" "$SYSROOT/etc"
    fi
}

find_orphans() {
    local op="$1"
    podman start repo-build

    declare store_pkgs
    local used_packages
    store_pkgs="$(podman exec --privileged repo-build \
        find /.repo/store -mindepth 1 -maxdepth 1)"
    store_pkgs="$(awk -F"/" '{print $NF}' <<< "$store_pkgs" | sort)"
    used_packages="$(podman exec --privileged repo-build bash -c 'cat /.repo/deployments/*/pkgs')"
    used_packages="$(sort -u <<< "$used_packages" | sed "s/$/.rpm/")"
    local orphans
    orphans="$(comm -23 <(printf "%s" "$store_pkgs") <(printf "%s" "$used_packages"))"
    if [[ "$op" == "get" ]]; then
        printf "%s\n" "$orphans"
    elif [[ "$op" == "rm" ]]; then
        printf "%s" "$orphans" | sed "s/^/\/.repo\/store\//" | xargs podman exec --privileged repo-build \
            rm -rf
    fi

    podman stop -t 2 repo-build &>/dev/null
}

cleanup_dep() {
    local deployment="$1"
    umount -Rfl "$SYSROOT/.repo/deployments/$deployment/"* 2>/dev/null || :
    if [[ -f "$SYSROOT/boot/loader/entries/$deployment.conf" ]]; then
        rm -f "$SYSROOT/boot/loader/entries/$deployment.conf"
    elif [[ -f "$SYSROOT/boot/EFI/Linux/$deployment.efi" ]]; then
        rm -f "$SYSROOT/boot/EFI/Linux/$deployment.efi"
    fi
    if [[ -d "$SYSROOT/boot/$deployment" ]]; then
        rm -rf "$SYSROOT/boot/$deployment"
    fi
    if [[ -d "$SYSROOT/tmp/$deployment" ]]; then
        rm -rf "$SYSROOT/tmp/$deployment"
    fi
    if [[ -d "$SYSROOT/.repo/deployments/$deployment" ]]; then
        rm -rf "$SYSROOT/.repo/deployments/$deployment"
    fi
    if [[ -d "/tmp/$deployment" ]]; then
        rm -rf "/tmp/$deployment"
    fi
    podman stop -t 1 repo-build &>/dev/null
    printf "Cleaned up deployment %s\n" "$deployment"
}

dep() {
    local replace="$1"
    local update="$2"
    local create="$3"
    local drop="$4"

    if [[ "$replace" == "1" ]]; then
        podman create --privileged --name repo-build --replace -ti \
            --volume "$SYSROOT/.repo":/.repo \
            --volume "$SYSROOT/etc/repo/scripts":/scripts \
            --volume /tmp:/tmp \
            "$CONTAINER_IMAGE"
    fi
    podman start repo-build
    if [[ "$replace" == "1" ]]; then
        podman exec --privileged repo-build dnf install -y dnf5-plugins
    fi
    if [[ "$update" == "1" && "$replace" == "0" ]]; then
        podman exec --privileged repo-build dnf check-upgrade --refresh -y
    fi

    if [[ -f "$SYSROOT/etc/repo/scripts/pre.sh" ]]; then
        printf "Running pre script...\n"
        podman exec --privileged repo-build \
            bash /scripts/pre.sh
    fi

    podman exec --privileged repo-build dnf makecache -y --use-host-config --installroot /empty
    declare pkg_list
    pkg_list="$(get_pkg_list "$SYSROOT/etc/repo/list.pkgs")"
    export SYSROOT
    export -f exists_or_install
    export -f dnf_download
    declare dnf_transaction
    dnf_transaction="$(get_dnf_transaction "/empty" pkg_list | tac)"
    populate_store "$dnf_transaction"
    export -n SYSROOT
    export -n exists_or_install
    export -n dnf_download

    if [[ "$create" == "1" ]]; then
        export SYSROOT
        export -f create_deployment
        export -f get_next_deployment
        export -f get_deployments
        export -f install_package
        create_deployment "$dnf_transaction" "$drop"
        export -n SYSROOT
        export -n create_deployment
        export -n get_next_deployment
        export -n get_deployments
        export -n install_package
    fi

    podman stop -t 2 repo-build &>/dev/null
}

case "$SUBCMD" in
    "none")
        printf "No subcommand was specified!\n"
        exit 1
        ;;
    "dep")
        printf "Creating new deployment...\n"
        dep "0" "0" "1" "$SUBARG"
        ;;
    "update")
        printf "Updating store and creating new deployment...\n"
        dep "0" "1" "1" "$SUBARG"
        ;;
    "recreate")
        printf "Recreating build container and rebuilding store...\n"
        dep "1" "0" "0" "$SUBARG"
        ;;
    "get-orphans")
        printf "Finding orphaned paths in the store...\n"
        find_orphans "get"
        ;;
    "status")
        get_dep_stati "$SUBARG"
        ;;
    "gc-store")
        printf "Removing unused store paths...\n"
        find_orphans "rm"
        ;;
    "gc-deps")
        printf "Collecting broken deps...\n"
        gc_defective
        ;;
    "gc")
        gc_all
        ;;
    "diff")
        diff_deps "$SUBARG" "$SUBSUBARG"
        ;;
    "activate")
        printf "Activating deployment %s\n" "$SUBARG"
        activate_dep "$SUBARG"
        ;;
    "init")
        printf "Initiating repo on the host system...\n"
        init_repo
        ;;
esac
